"""DIA-130: 16 x 16 clipboard icon for the `Punch list (n)` button in the view-nav row.

Flat front view, not isometric: it sits in page chrome next to text, not in the
building. It borrows the building's materials so it reads as the same place — the
desk-wood board (lit left, `desk-wood-dark` on the shaded right and foot, light from
the top-left as everywhere), the badge-reader metal for the clip, `paper` for the sheet
and the badge reader's green for the ticks. Two items ticked, one still open: it is a
punch list, not a certificate.

Shipped at 1x and nearest-neighbour 2x / 3x (integer scaling only, style.md) under
public/sprites/ui/. Regenerate: `python3 -m art.src.sprites.ui_clipboard`.
"""
from __future__ import annotations

import json
import os

from art.src.dsl import from_rows, save_png, scale_nn

MAP = {
    "O": "outline",
    "W": "desk-wood",
    "D": "desk-wood-dark",
    "C": "badge-body",
    "c": "chair-mid",
    "P": "paper",
    "T": "wall-shadow",
    "G": "badge-green",
    "L": "chair-dark",
}

# Paper interior is cols 3-12; the board shows at col 2 (lit) and col 13 (shaded).
_PAPER = [
    "PPPPPPPPPT",  # r4
    "PPPGPPPPPT",  # r5  tick, upper stroke
    "PGGPPLLLLT",  # r6  tick, lower stroke + line
    "PPPPPPPPPT",  # r7
    "PPPGPPPPPT",  # r8
    "PGGPPLLLLT",  # r9
    "PPPPPPPPPT",  # r10
    "PPPPPPPPPT",  # r11
    "PccPPLLLLT",  # r12 open item: empty dash, line
    "TTTTTTTTTT",  # r13 paper foot in shade
]

ROWS = [
    ".....OOOOOO.....",
    ".OOOOOCCCcOOOOO.",
    ".OWWOCCCCCcOWDO.",
    ".OWPOOOOOOOOPDO.",
    *(".OW" + p + "DO." for p in _PAPER),
    ".OWDDDDDDDDDDDO.",
    ".OOOOOOOOOOOOOO.",
]

UI_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
    "public", "sprites", "ui",
)
SCALES = (1, 2, 3)


def build():
    return from_rows(ROWS, MAP)


def main():
    icon = build()
    assert (icon.w, icon.h) == (16, 16)
    files = {}
    for s in SCALES:
        name = "clipboard.png" if s == 1 else f"clipboard@{s}x.png"
        save_png(icon if s == 1 else scale_nn(icon, s), os.path.join(UI_DIR, name))
        files[f"{s}x"] = name
    manifest = {
        "_comment": "UI chrome sprites (not scene sprites). Generated by "
                    "`python3 -m art.src.sprites.ui_clipboard`; do not hand-edit. "
                    "Display at w x h CSS px with image-rendering: pixelated.",
        "clipboard": {"w": icon.w, "h": icon.h, "files": files},
    }
    with open(os.path.join(UI_DIR, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print("wrote", ", ".join(files.values()), "+ manifest.json to", UI_DIR)


if __name__ == "__main__":
    main()
