// PH1-03: typed accessors over the generated content.json.
//
// content.json is generated by scripts/build-content.ts (wired as
// `prebuild`, see package.json) from docs/content/*.md — the docs are the
// single source of truth (00-VISION.md: "Content is the product"). Never
// hand-edit content.json and never read docs/content/*.md at runtime; this
// module is the only supported way the rest of the app reads content.
import contentJson from './content.json';
import type { Band, BandId, Beyond, ContentJson, Copy, Gag, PanelFields, Ui } from '../../scripts/build-content';

// The `as unknown as ContentJson` cast (rather than a plain `as`) is
// because this repo has no `resolveJsonModule` in tsconfig.json (out of
// this brief's boundaries — scripts/build-content.ts, src/content/**,
// tests, and package.json scripts only) and no `tsc --noEmit` step exists
// yet to need it; Vite resolves the JSON import at build/bundle time
// regardless. schema.json + build-content.ts's own validation are what
// actually guarantee this shape, not this cast.
const content = contentJson as unknown as ContentJson;

/** The band with this id, or undefined if content.json somehow lacks one (it always has all eight). */
export function getBand(id: BandId): Band | undefined {
  return content.bands.find((band) => band.id === id);
}

/** Every gag whose band is `id`, in the order they appear in content.json (sorted by id). */
export function getGagsForBand(id: BandId): Gag[] {
  return content.gags.filter((gag) => gag.band === id);
}

/** The single "1,000+" panel + its translation table. */
export function getBeyond(): Beyond {
  return content.beyond;
}

/** All bands, in content.json order (80, 150, 220, 360, 490, 610, 750, beyond). */
export function getBands(): Band[] {
  return content.bands;
}

/** Every gag, in content.json order (banded, then by id). */
export function getGags(): Gag[] {
  return content.gags;
}

/** The G3.A ambient hover text (no panel). */
export function getAmbientHover(): string {
  return content.ambient.hover;
}

/** Toggle/share/OG copy from TONE.md §"Toggle and share copy". */
export const copy: Copy = content.copy;

/**
 * Contact info for the "Talk to Josh" link (R-12): a LinkedIn URL plus an
 * email split into { user, domain }. content.json never carries the joined
 * address — assemble it here, client-side only, e.g.
 * `${getContact().email.user}@${getContact().email.domain}`, so it never
 * appears as a plain string in served source or a `mailto:` in markup.
 */
export function getContact(): Copy['contact'] {
  return content.copy.contact;
}

export type { Band, BandId, Beyond, ContentJson, Copy, Gag, PanelFields, Ui };
